project: 
  type: website
  output-dir: docs

website:
  title: "Lexi Soelberg - Research & Statistics Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Lexi Soelberg  2026©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/lexi-soelberg-5494363a5/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Statistics Projects"
        href: Statistics_Projects.qmd
      - text: "Research Papers"
        href: Research_Papers.qmd
      - text: "Temporal Envy"
        href: Temporal_Envy.qmd
      - text: "Married Differences"
        href: Married_Differences.qmd
      - text: "Industrial-Organizational Data"
        href: Industrial_Organizational_Data.qmd
      - text: "Conferences"
        href: Conferences.qmd
  
  # learn more about navigation here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Statistics Projects"
      style: "docked"
      background: light
      contents:
        - text: "Overview & Skills"
          href: Statistics_Projects.qmd
        - text: "---"
        
        # --- SECTION 1: INTERMEDIATE STATS ---
        - section: "Intermediate Stats"
          id: "intermediate-stats"
          collapsed: true
          contents:
            - text: "Project 1: T-Test"
              href: Statistics_Projects/Intermediate_Stats/project1.qmd
            - text: "Project 2: Wilcoxon Test"
              href: Statistics_Projects/Intermediate_Stats/project2.qmd
            - text: "Project 3: Kruskall-Wallis Test"
              href: Statistics_Projects/Intermediate_Stats/project3.qmd
            - text: "Project 4: Two-Way ANOVA"
              href: Statistics_Projects/Intermediate_Stats/project4.qmd
            - text: "Project 5: Simple Linear Regression"
              href: Statistics_Projects/Intermediate_Stats/project5.qmd
            - text: "Project 6: Logistic Regression"
              href: Statistics_Projects/Intermediate_Stats/project6.qmd
            - text: "Project 7: Chi-Squared Test"
              href: Statistics_Projects/Intermediate_Stats/project7.qmd
            - text: "Project 8: Client Project - Rent"
              href: Statistics_Projects/Intermediate_Stats/project8.qmd
            - text: "Project 9: Multiple Linear Regression"
              href: Statistics_Projects/Intermediate_Stats/project9.qmd
            - text: "Project 10: Consulting Project"
              href: Statistics_Projects/Intermediate_Stats/project10.qmd
            - text: "---"
        
        # --- SECTION 2: EXPERIMENTAL DESIGN ---
        - section: "Experimental Design"
          id: "experimental-design"
          collapsed: true
          contents:
             - text: "Project 1: Randomized Blocks"
               href: Statistics_Projects/Experimental_Design/project1.qmd
        #     - text: "Project 2: Factorial ANOVA"
        #       href: Statistics_Projects/Experimental_Design/project2.qmd
        #     - text: "Project 3"
        #       href: Statistics_Projects/Experimental_Design/project3.qmd
        #     - text: "Project 4"
        #       href: Statistics_Projects/Experimental_Design/project4.qmd
        #     - text: "Project 5"
        #       href: Statistics_Projects/Experimental_Design/project5.qmd
        #     - text: "Project 6"
        #       href: Statistics_Projects/Experimental_Design/project6.qmd
        #     - text: "Project 7"
        #       href: Statistics_Projects/Experimental_Design/project7.qmd
        #     - text: "Project 8"
        #       href: Statistics_Projects/Experimental_Design/project8.qmd
        #     - text: "Project 9"
        #       href: Statistics_Projects/Experimental_Design/project9.qmd
        #     - text: "Project 10"
        #       href: Statistics_Projects/Experimental_Design/project10.qmd
        #     - text: "Project 11"
        #       href: Statistics_Projects/Experimental_Design/project11.qmd
        #     - text: "Project 12"
        #       href: Statistics_Projects/Experimental_Design/project12.qmd
        - text: "---"
        
        # --- SECTION 3: APPLIED LINEAR REGRESSION ---
        - section: "Applied Linear Regression"
          id: "linear-regression"
          collapsed: true
          contents:
             - text: "Project 1: Predicting the Weather"
               href: Statistics_Projects/Linear_Regression/project1.qmd
             - text: "Project 2: Residuals, Sum of Squares, & R-Squared"
               href: Statistics_Projects/Linear_Regression/project2.qmd
             - text: "Project 3: Car Selling Price"
               href: Statistics_Projects/Linear_Regression/project3.qmd
             - text: "Project 4: Midterm Decision"
               href: Statistics_Projects/Linear_Regression/project4.qmd
             - text: "Project 5: Regression Battleship"
               href: Statistics_Projects/Linear_Regression/project5.qmd
             - text: "Project 6: House Selling Price"
               href: Statistics_Projects/Linear_Regression/project6.qmd
             - text: "Project 7: Logistic Regression"
               href: Statistics_Projects/Linear_Regression/project7.qmd
             - text: "Project 8: Consulting Project"
               href: Statistics_Projects/Linear_Regression/project8.qmd
             - text: "---"
        
        # --- SECTION 4: DATA WRANGLING & VISUALIZATION ---
        - section: "Data Wrangling & Visualizations"
          id: "data-wrangling"
          collapsed: true
          contents:
        #     - text: "Project 1: Tidyverse Cleaning"
        #       href: Statistics_Projects/Data_Wrangling/project1.qmd
        #     - text: "Project 2: ggplot2 Dashboards"
        #       href: Statistics_Projects/Data_Wrangling/project2.qmd
        #     - text: "Project 3"
        #       href: Statistics_Projects/Data_Wrangling/project3.qmd
        #     - text: "Project 4"
        #       href: Statistics_Projects/Data_Wrangling/project4.qmd
        #     - text: "Project 5"
        #       href: Statistics_Projects/Data_Wrangling/project5.qmd
        #     - text: "Project 6"
        #       href: Statistics_Projects/Data_Wrangling/project6.qmd
        #     - text: "Project 7"
        #       href: Statistics_Projects/Data_Wrangling/project7.qmd
        #     - text: "Project 8"
        #       href: Statistics_Projects/Data_Wrangling/project8.qmd
        #     - text: "Project 9"
        #       href: Statistics_Projects/Data_Wrangling/project9.qmd
        #     - text: "Project 10"
        #       href: Statistics_Projects/Data_Wrangling/project10.qmd
        #     - text: "Project 11"
        #       href: Statistics_Projects/Data_Wrangling/project11.qmd
        #     - text: "Project 12"
        #       href: Statistics_Projects/Data_Wrangling/project12.qmd
              - text: "---"
              
    - title: "Research Papers"
      style: "docked"
      background: light
      contents:
        - text: "Research Papers"
          href: Research_Papers.qmd
        - text: "---"
        - text: "Project 1"
          href: Research_Papers/project1.qmd
        - text: "---"
        - text: "Project 2"
          href: Research_Papers/project2.qmd
        - text: "---"
        - text: "Project 3"
          href: Research_Papers/project3.qmd
        - text: "---"

    - title: "Temporal Envy"
      style: "docked"
      background: light
      contents:
        - text: "Temporal Envy"
          href: Temporal_Envy.qmd
        - text: "---"
        - text: "Poster Presentation"
          href: Temporal_Envy/poster1.qmd
        - text: "---"
        - text: "Abstract"
          href: Temporal_Envy/abstract1.qmd
        - text: "---"
        - text: "Index"
          href: Temporal_Envy/index1.qmd
        - text: "---"

    - title: "Married Differences"
      style: "docked"
      background: light
      contents:
        - text: "Married Differences"
          href: Married_Differences.qmd
        - text: "---"
        - text: "Poster Presentation"
          href: Married_Differences/poster2.qmd
        - text: "---"
        - text: "Abstract"
          href: Married_Differences/abstract2.qmd
        - text: "---"
        - text: "Index"
          href: Married_Differences/index2.qmd
        - text: "---"

    - title: "Industrial-Organizational Data"
      style: "docked"
      background: light
      contents:
        - text: "Industrial-Organizational Data"
          href: Industrial_Organizational_Data.qmd
        - text: "---"
        - text: "Project 1"
          href: Industrial_Organizational_Data/project1.qmd
        - text: "---"
        - text: "Project 2"
          href: Industrial_Organizational_Data/project2.qmd
        - text: "---"

    - title: "Conferences"
      style: "docked"
      background: light
      contents:
        - text: "Conferences"
          href: Conferences.qmd
        - text: "---"
        - text: "Research & Creative Works"
          href: Conferences/RCW.qmd
        - text: "---"
        - text: "Rocky Mountain Psychological Association - 2026"
          href: Conferences/RMPA2026.qmd
        - text: "---"
        - text: "Rocky Mountain Psychological Association - 2027"
          href: Conferences/RMPA2027.qmd
        - text: "---"

format:  
  html:
    theme: 
      light: flatly 
      dark: darkly
    css: styles.css
    toc: true