project: 
  type: website
  output-dir: docs

website:
  title: "Lexi Soelberg - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Lexi Soelberg  2026©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/lexi-soelberg-5494363a5/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Lexi's Resume"
        file: resume.qmd
      - text: "Statistics Projects"
        file: Statistics_Projects.qmd
      - text: "Research Papers"
        file: Research_Papers.qmd
      - text: "Temporal Envy"
        file: Temporal_Envy.qmd
      - text: "Married_Differences"
        file: Married_Differnces.qmd
      - text: "Industrial-Organizational Data"
        file: Industrial_Organizational_Data.qmd
      - text: "Conferences"
        file: Conferences.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Statistics Projects"
      style: "docked"
      background: light
      contents:
        - text: "Statistics Projects"
          file: Statistics_Projects.qmd
        - text: "---"
        - text: "Project 1"
          file: Statistics_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Statistics_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Statistics_Projects/project3.qmd
        - text: "---"
    - title: "Research Papers"
      style: "docked"
      background: light
      contents:
        - text: "Research Papers"
          file: Research_Papers.qmd
        - text: "---"
        - text: "Project 1"
          file: Research_Papers/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Research_Papers/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Research_Papers/project3.qmd
        - text: "---"
    - title: "Temporal Envy"
      style: "docked"
      background: light
      contents:
        - text: "Temporal Envy"
          file: Temporal_Envy.qmd
        - text: "---"
        - text: "Project 1"
          file: Temporal_Envy/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Temporal_Envy/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Temporal_Envy/project3.qmd
        - text: "---"
    - title: "Married Differnces"
      style: "docked"
      background: light
      contents:
        - text: "Married Differnces"
          file: Married_Differnces.qmd
        - text: "---"
        - text: "Project 1"
          file: Married_Differnces/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Married_Differnces/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Married_Differnces/project3.qmd
        - text: "---"
    - title: "Industrial-Organizational Data"
      style: "docked"
      background: light
      contents:
        - text: "Industrial-Organizational Data"
          file: Industrial_Organizational_Data.qmd
        - text: "---"
        - text: "Project 1"
          file: Industrial_Organizational_Data/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Industrial_Organizational_Data/project2.qmd
        - text: "---"
    - title: "Conferences"
      style: "docked"
      background: light
      contents:
        - text: "Conferences"
          file: Conferences.qmd
        - text: "---"
        - text: "Project 1"
          file: Conferences/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Conferences/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Conferences/project3.qmd
        - text: "---"

  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



